### ISSUE TITLE
1.0.1 Overlay

### ISSUE THREAD

**Issue by TheVigilantWolf** [tinyhoot/ShipLobby#3]
Looks like the new update isn't working with steam overlay for me, so invites aren't possible. Dragged everything from zip to game file. Shift+Tab brings no overlay up.

**Comment by tinyhoot** [comment]
That's an issue elsewhere. Nothing about this mod even has the option to influence how the steam overlay works

**Comment by TheVigilantWolf** [comment]
Only happens with your mod installed, removing your files from my game allows me to send invites again.

**Comment by tinyhoot** [comment]
Is it not being able to send invites or the overlay refusing to open up at all?

**Comment by TheVigilantWolf** [comment]
The invite system in LC is integrated into the steam overlay. The window that popups after clicking send invite is a steam overlay window. I'm not having this issue anymore on the newest version. Window shows up now.
